### ISSUE TITLE
Shell script to install riff using kapp and ytt

### ISSUE THREAD

**Issue by jldec** [projectriff/charts#103]
A a riff user, i would like to install riff using kapp and ytt by running a simple bash script. This would be easier than copying the commands one-by-one from the README.

**Comment by scothis** [comment]
I'm not in favor of creating a "simple bash script" as it's not something we'd want to support. What this issue really seems to be asking for is an installer, which should be considered and properly designed.

**Comment by jldec** [comment]
I guess we'll solve this in the getting started docs maybe by pointing to the script in [projectriff-demo](https://github.com/projectriff-demo/demo/blob/master/riff-kapp-install.sh).
