### ISSUE TITLE
Uninstall of CRDs hang if there was a Knative Route defined

### ISSUE THREAD

**Issue by trisberg** [projectriff/charts#22]
If I delete the helm install and run the command do remove the CRDs I can get into a situation where a `Route` can't be delete. Looks like there is a finalizer that hold things up:

```
    finalizers:
    - routes.serving.knative.dev
```

**Comment by trisberg** [comment]
We used to delete all knative app resources to avoid this - https://github.com/projectriff/riff/blob/v0.3.x/pkg/core/system.go#L378-L393

**Comment by scothis** [comment]
@trisberg are you sure this fixes the issue and not that you happened to get lucky?

See https://github.com/knative/serving/issues/4732
