### ISSUE TITLE
Cleanup CRDs when the chart is deleted/reinstalled

### ISSUE THREAD

**Issue by scothis** [projectriff/charts#6]
Helm orphans CRDs installed with the crd-install hook, and then refuses to reinstall the chart because the CRDs exist. We should make sure that the CRDs are removed when the chart in uninstalled.

See https://github.com/helm/helm/blob/master/docs/charts_hooks.md#automatically-delete-hook-from-previous-release

**Comment by scothis** [comment]
Documented a work around in #7

**Comment by trisberg** [comment]
The command to delete the Istio CRDs didn't seem to work. The CRDs don't have any labels

```
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2019-07-22T18:04:09Z"
  generation: 1
  name: httpapispecs.config.istio.io
  resourceVersion: "1872"
  selfLink: /apis/apiextensions.k8s.io/v1beta1/customresourcedefinitions/httpapispecs.config.istio.io
  uid: 1a8f7277-acab-11e9-b311-00155d091220
spec:
...
```

**Comment by scothis** [comment]
@trisberg good catch. Because the CRDs are not installed directly via helm, they don't have that label. On the flip side, because they are not installed directly via helm, if their existence will not bork the reinstall.

To actually delete all of the Istio CRDs you'll need something more like:
```
kubectl get crds -oname | grep '\.istio\.io$' | xargs kubectl delete
```

The danger in this command is that it could delete other CRDs that are also in an istio.io api group that were installed in some other way.

**Comment by scothis** [comment]
This is as done as it's going to get with Helm 2
